version: "3"

volumes:
    postgres-db:
    postgres-test:

services:
    api:
        command: python main.py
        build: .
        depends_on:
            - database
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
        env_file:
            - 'environments/development.env'

    database:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data
        env_file:
            - 'environments/development.env'

    testdb:
        image: postgres
        environment:
            - POSTGRES_DB=test-db
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        restart: always
        ports:
            - "5433:5432"
        volumes:
            - postgres-test:/var/lib/postgresql/data
