version: "3"

volumes:
    postgres-db:

services:
    api:
        command: python main.py
        build: .
        depends_on:
            - database
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        env_file:
            - 'environments/development.env'

    database:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data
        env_file:
            - 'environments/development.env'
