"""92 - quotes with user, quotes with items (relational)

Revision ID: d2199389b6a2
Revises: a91601e70b47
Create Date: 2022-04-13 21:41:13.532882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2199389b6a2'
down_revision = 'a91601e70b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quote_num', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['md.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_num'),
    schema='md'
    )
    op.create_table('items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('unit_value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('quote_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['md.quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='md'
    )
    op.create_index(op.f('ix_md_items_quantity'), 'items', ['quantity'], unique=False, schema='md')
    op.create_index(op.f('ix_md_items_description'), 'items', ['description'], unique=False, schema='md')
    op.create_index(op.f('ix_md_items_item_name'), 'items', ['item_name'], unique=False, schema='md')
    op.create_index(op.f('ix_md_items_unit_value'), 'items', ['unit_value'], unique=False, schema='md')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_md_items_unit_value'), table_name='items', schema='md')
    op.drop_index(op.f('ix_md_items_item_name'), table_name='items', schema='md')
    op.drop_index(op.f('ix_md_items_description'), table_name='items', schema='md')
    op.drop_index(op.f('ix_md_items_quantity'), table_name='items', schema='md')
    op.drop_table('items', schema='md')
    op.drop_table('quotes', schema='md')
    op.drop_table('users', schema='md')
    # ### end Alembic commands ###